#!/usr/bin/env bash

# Helpers
prog_dir=$(dirname $(realpath "$0"))
. "$prog_dir/lib"

# Options
while getopts "h" opt; do
    case "$opt" in
	   h) cat <<EOF
alias - Set an alias for a workspace.

USAGE

    alias [-h] WORKSPACE [ALIAS]

OPTIONS

    -h    Show this help text.

ARGUMENTS

    WORKSPACE    Name of workspace to set alias.
    ALIAS        Single word (can have underscores & dashes) alias. Empty or "-" to
                 remove an alias. Cannot be "@" since it is reserved to refer to the
                 default workspace.

BEHAVIOR

    Sets or removes a workspace's alias. Then with any command which takes a 
    workspace name as an argument an alias can be provided instead.

    No two workspaces can have the same alias.

EOF
		 exit 0
		 ;;
	   '?') die "Unknown option" ;;
    esac
done

# Arguments
shift $((OPTIND-1))

workspace=$(resolve_alias "$1")
shift
if [ -z "$workspace" ]; then
    die "WORKSPACE argument required"
fi

alias="$1"
shift

if [[ "$alias" == "@" ]]; then
    die "ALIAS cannot be \"@\" as this is used to signify the default workspace"
fi

if [ -n "$alias" ]; then
    clash=$(resolve_alias "$alias" nodie)
    if [ -n "$clash" ]; then
	   die "Cannot set $workspace workspace's alias to \"$alias\", the workspace $clash has the same alias"
    fi
fi

# Set alias
if [[ "$alias" == "-" ]]; then # "-" signifies the alias should be empty
    alias=""
fi

echo "$alias" > "$ALIASES_DIR/$workspace"
