#!/usr/bin/env bash

# Helpers
prog_dir=$(realpath $(dirname "$0"))
. "$prog_dir/lib"

# Options
while getopts "h" opt; do
    case "h" in
	   h) cat <<EOF
note - Set note for workspace.

USAGE

    note [-h] WORKSPACE NOTE...

OPTIONS

    -h    Show this help text.

ARGUMENTS

    WORKSPACE    Name of workspace to set note.
    NOTE...      Any number of words, note.

EOF
		 exit 0
		 ;;
	   '?') die "Unknown option" ;;
    esac
done

# Arguments
shift $((OPTIND-1))

workspace=$(resolve_alias "$1")
shift
if [ -z "$workspace" ]; then
    die "WORKSPACE argument required"
fi

note="$@"

# Set note
echo "$note" > "$NOTES_DIR/$workspace"
