#!/usr/bin/env bash

# Helpers
prog_dir=$(dirname $(realpath "$0"))
. "$prog_dir/lib"

# Options
while getopts "h" opt; do
    case "$opt" in
	   h) cat <<EOF
note - Set note for workspace.

USAGE

    note [-h] WORKSPACE NOTE...

OPTIONS

    -h    Show this help text.

ARGUMENTS

    WORKSPACE    Name of workspace to set note.
    NOTE...      Any number of words, note. If empty or "-" the note will be set
                 to empty.

BEHAVIOR

    Sets the note for a workspace. This can be used to save arbitrary comments
    about a workspace.

EOF
		 exit 0
		 ;;
	   '?') die "Unknown option" ;;
    esac
done

# Arguments
shift $((OPTIND-1))

workspace=$(resolve_alias "$1")
shift
if [ -z "$workspace" ]; then
    die "WORKSPACE argument required"
fi

note="$@"

# Set note
if [[ "$note" == "-" ]]; then # Value of "-" indicates note should be empty.
    note=""
fi
echo "$note" > "$NOTES_DIR/$workspace"
