#!/usr/bin/env bash

# Helpers
prog_dir=$(realpath $(dirname "$0"))
. "$prog_dir/lib"

# Options
while getopts "h" opt; do
    case "h" in
	   h) cat <<EOF
pwd - Get location of workspace.

USAGE

    note [-h] WORKSPACE

OPTIONS

    -h    Show this help text.

ARGUMENTS

    WORKSPACE    Name of workspace for which to get directory.

EOF
		 exit 0
		 ;;
	   '?') die "Unknown option" ;;
    esac
done

# Arguments
shift $((OPTIND-1))

workspace=$(resolve_alias "$1")
shift
if [ -z "$workspace" ]; then
    die "WORKSPACE argument required"
fi

# Print dir
echo "$WORKSPACES_DIR/$workspace"
